addons:
  sonarcloud:
    organization: "nefarioustim-github"

sudo: required

language: python

git:
  depth: false

services: docker

before_install: docker pull nefarioustim/cerberus-auth

install: true

script:
  - docker run -v ${PWD}:/app nefarioustim/cerberus-auth pipenv run pytest
  - sonar-scanner
