addons:
  sonarcloud:
    organization: "nefarioustim-github"

sudo: required

language: python

git:
  depth: false

services: docker

before_install:
  - make build

install: true

script:
  - make test
  - sonar-scanner
