sudo: required

language: python

services: docker

before_install: docker pull nefarioustim/cerberus-auth

install: true

script: docker run -v ${PWD}:/app nefarioustim/cerberus-auth pipenv run pytest
