version: "3.7"

services:
  app:
    build: .
    image: nefarioustim/cerberus-auth
    container_name: app
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - backend

  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${STORAGE_USER}
      POSTGRES_PASSWORD: ${STORAGE_PASSWORD}
      POSTGRES_DB: cerberusauth
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${STORAGE_USER} cerberusauth"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local

networks:
  backend:
