---
version: 1

formatters:
    simple:
        format: "%(asctime)s - %(levelname)-8s - %(name)s - %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
    console:
        class: logging.StreamHandler
        formatter: simple
        level: INFO

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: "/var/log/cerberusinfo.log"
        encoding: utf-8
        maxBytes: 10485760 # 10MB
        backupCount: 20

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: "/var/log/cerberuserror.log"
        encoding: utf-8
        maxBytes: 10485760 # 10MB
        backupCount: 20

loggers:
    root:
        level: INFO
        handlers: [console, info_file_handler, error_file_handler]
